#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Arquivo de configuração para o Google Business Finder
"""

import os
from typing import Dict, Any

# Configurações da API
API_CONFIG = {
    'base_url': 'https://maps.googleapis.com/maps/api/place',
    'language': 'pt-BR',
    'region': 'br',
    'timeout': 30,
    'max_retries': 3
}

# Configurações de busca
SEARCH_CONFIG = {
    'default_radius': 50000,  # 50km em metros
    'max_results': 100,
    'delay_between_requests': 0.1,  # segundos
    'delay_between_pages': 2,  # segundos
}

# Configurações de exportação
EXPORT_CONFIG = {
    'default_format': 'xlsx',
    'sheet_name': 'Empresas',
    'include_index': False,
    'timestamp_format': '%Y%m%d_%H%M%S'
}

# Configurações de logging
LOGGING_CONFIG = {
    'level': 'INFO',
    'format': '%(asctime)s - %(levelname)s - %(message)s',
    'file': 'google_business_finder.log',
    'max_file_size': 10 * 1024 * 1024,  # 10MB
    'backup_count': 5
}

# Campos padrão para busca de detalhes
DEFAULT_FIELDS = [
    'name',
    'formatted_phone_number',
    'website',
    'formatted_address',
    'rating',
    'user_ratings_total',
    'types',
    'business_status',
    'geometry',
    'place_id'
]

# Mapeamento de tipos de negócio para português
BUSINESS_TYPE_MAPPING = {
    'restaurant': 'Restaurante',
    'store': 'Loja',
    'pharmacy': 'Farmácia',
    'hospital': 'Hospital',
    'school': 'Escola',
    'bank': 'Banco',
    'gas_station': 'Posto de Gasolina',
    'car_repair': 'Oficina Mecânica',
    'beauty_salon': 'Salão de Beleza',
    'gym': 'Academia',
    'hotel': 'Hotel',
    'movie_theater': 'Cinema',
    'park': 'Parque',
    'museum': 'Museu',
    'library': 'Biblioteca',
    'police': 'Delegacia',
    'fire_station': 'Corpo de Bombeiros',
    'post_office': 'Correios',
    'supermarket': 'Supermercado',
    'bakery': 'Padaria',
    'butcher_shop': 'Açougue',
    'florist': 'Floricultura',
    'jewelry_store': 'Joalheria',
    'shoe_store': 'Sapataria',
    'clothing_store': 'Loja de Roupas',
    'electronics_store': 'Loja de Eletrônicos',
    'book_store': 'Livraria',
    'toy_store': 'Loja de Brinquedos',
    'pet_store': 'Pet Shop',
    'hardware_store': 'Casa de Ferramentas',
    'furniture_store': 'Móveis',
    'car_dealer': 'Concessionária',
    'real_estate_agency': 'Imobiliária',
    'travel_agency': 'Agência de Viagens',
    'insurance_agency': 'Seguradora',
    'lawyer': 'Advocacia',
    'dentist': 'Dentista',
    'doctor': 'Médico',
    'veterinary_care': 'Veterinário',
    'car_wash': 'Lava Jato',
    'laundry': 'Lavanderia',
    'dry_cleaner': 'Tinturaria',
    'barber_shop': 'Barbearia',
    'nail_salon': 'Manicure',
    'spa': 'Spa',
    'massage_therapy': 'Massoterapia',
    'chiropractor': 'Quiropraxista',
    'physiotherapist': 'Fisioterapeuta',
    'psychologist': 'Psicólogo',
    'accountant': 'Contador',
    'architect': 'Arquiteto',
    'engineer': 'Engenheiro',
    'consultant': 'Consultor',
    'photographer': 'Fotógrafo',
    'designer': 'Designer',
    'artist': 'Artista',
    'musician': 'Músico',
    'teacher': 'Professor',
    'trainer': 'Personal Trainer',
    'coach': 'Coach',
    'mentor': 'Mentor',
    'advisor': 'Consultor',
    'planner': 'Planejador',
    'organizer': 'Organizador',
    'cleaner': 'Limpeza',
    'maintenance': 'Manutenção',
    'repair': 'Reparo',
    'installation': 'Instalação',
    'construction': 'Construção',
    'renovation': 'Reforma',
    'landscaping': 'Paisagismo',
    'gardening': 'Jardinagem',
    'pool_service': 'Serviço de Piscina',
    'security': 'Segurança',
    'transportation': 'Transporte',
    'delivery': 'Entrega',
    'courier': 'Mensageiro',
    'logistics': 'Logística',
    'warehouse': 'Armazém',
    'factory': 'Fábrica',
    'office': 'Escritório',
    'coworking_space': 'Espaço de Coworking',
    'meeting_room': 'Sala de Reunião',
    'conference_center': 'Centro de Conferência',
    'event_space': 'Espaço para Eventos',
    'wedding_venue': 'Local para Casamentos',
    'party_venue': 'Local para Festas',
    'recreation_center': 'Centro de Recreação',
    'sports_complex': 'Complexo Esportivo',
    'stadium': 'Estádio',
    'arena': 'Arena',
    'track': 'Pista',
    'court': 'Quadra',
    'field': 'Campo',
    'pool': 'Piscina',
    'beach': 'Praia',
    'mountain': 'Montanha',
    'forest': 'Floresta',
    'park': 'Parque',
    'garden': 'Jardim',
    'zoo': 'Zoológico',
    'aquarium': 'Aquário',
    'planetarium': 'Planetário',
    'observatory': 'Observatório',
    'laboratory': 'Laboratório',
    'research_center': 'Centro de Pesquisa',
    'university': 'Universidade',
    'college': 'Faculdade',
    'institute': 'Instituto',
    'academy': 'Academia',
    'conservatory': 'Conservatório',
    'studio': 'Estúdio',
    'workshop': 'Oficina',
    'atelier': 'Ateliê',
    'gallery': 'Galeria',
    'exhibition': 'Exposição',
    'showroom': 'Showroom',
    'warehouse': 'Depósito',
    'storage': 'Armazenamento',
    'parking': 'Estacionamento',
    'garage': 'Garagem',
    'shelter': 'Abrigo',
    'refuge': 'Refúgio',
    'sanctuary': 'Santuário',
    'temple': 'Templo',
    'church': 'Igreja',
    'mosque': 'Mesquita',
    'synagogue': 'Sinagoga',
    'shrine': 'Santuário',
    'monument': 'Monumento',
    'memorial': 'Memorial',
    'cemetery': 'Cemitério',
    'graveyard': 'Cemitério',
    'mausoleum': 'Mausoléu',
    'tomb': 'Tumba',
    'grave': 'Túmulo',
    'burial': 'Enterro',
    'cremation': 'Crematório',
    'funeral_home': 'Funerária',
    'mortuary': 'Morgue',
    'coroner': 'Legista',
    'medical_examiner': 'Perito Médico',
    'pathologist': 'Patologista',
    'radiologist': 'Radiologista',
    'surgeon': 'Cirurgião',
    'anesthesiologist': 'Anestesista',
    'cardiologist': 'Cardiologista',
    'dermatologist': 'Dermatologista',
    'endocrinologist': 'Endocrinologista',
    'gastroenterologist': 'Gastroenterologista',
    'hematologist': 'Hematologista',
    'immunologist': 'Imunologista',
    'infectious_disease': 'Doenças Infecciosas',
    'nephrologist': 'Nefrologista',
    'neurologist': 'Neurologista',
    'oncologist': 'Oncologista',
    'ophthalmologist': 'Oftalmologista',
    'orthopedist': 'Ortopedista',
    'otolaryngologist': 'Otorrinolaringologista',
    'pediatrician': 'Pediatra',
    'psychiatrist': 'Psiquiatra',
    'pulmonologist': 'Pneumologista',
    'rheumatologist': 'Reumatologista',
    'urologist': 'Urologista',
    'gynecologist': 'Ginecologista',
    'obstetrician': 'Obstetra',
    'midwife': 'Parteira',
    'nurse': 'Enfermeiro',
    'paramedic': 'Paramédico',
    'emergency_medical_technician': 'Técnico de Emergência',
    'medical_assistant': 'Auxiliar Médico',
    'pharmacy_technician': 'Técnico de Farmácia',
    'laboratory_technician': 'Técnico de Laboratório',
    'radiology_technician': 'Técnico de Radiologia',
    'respiratory_therapist': 'Terapeuta Respiratória',
    'occupational_therapist': 'Terapeuta Ocupacional',
    'speech_therapist': 'Fonoaudiólogo',
    'physical_therapist': 'Fisioterapeuta',
    'massage_therapist': 'Massoterapeuta',
    'acupuncturist': 'Acupunturista',
    'chiropractor': 'Quiropraxista',
    'osteopath': 'Osteopata',
    'naturopath': 'Naturopata',
    'homeopath': 'Homeopata',
    'herbalist': 'Herbalista',
    'nutritionist': 'Nutricionista',
    'dietitian': 'Nutricionista',
    'personal_trainer': 'Personal Trainer',
    'fitness_instructor': 'Instrutor de Fitness',
    'yoga_instructor': 'Instrutor de Yoga',
    'pilates_instructor': 'Instrutor de Pilates',
    'dance_instructor': 'Instrutor de Dança',
    'music_teacher': 'Professor de Música',
    'art_teacher': 'Professor de Arte',
    'language_teacher': 'Professor de Idiomas',
    'math_teacher': 'Professor de Matemática',
    'science_teacher': 'Professor de Ciências',
    'history_teacher': 'Professor de História',
    'geography_teacher': 'Professor de Geografia',
    'literature_teacher': 'Professor de Literatura',
    'philosophy_teacher': 'Professor de Filosofia',
    'sociology_teacher': 'Professor de Sociologia',
    'psychology_teacher': 'Professor de Psicologia',
    'economics_teacher': 'Professor de Economia',
    'business_teacher': 'Professor de Administração',
    'computer_science_teacher': 'Professor de Informática',
    'engineering_teacher': 'Professor de Engenharia',
    'architecture_teacher': 'Professor de Arquitetura',
    'design_teacher': 'Professor de Design',
    'fashion_teacher': 'Professor de Moda',
    'culinary_teacher': 'Professor de Culinária',
    'bartending_teacher': 'Professor de Bartender',
    'wine_teacher': 'Professor de Vinhos',
    'coffee_teacher': 'Professor de Café',
    'tea_teacher': 'Professor de Chá',
    'beer_teacher': 'Professor de Cerveja',
    'spirits_teacher': 'Professor de Destilados',
    'cooking_teacher': 'Professor de Culinária',
    'baking_teacher': 'Professor de Confeitaria',
    'pastry_teacher': 'Professor de Pastelaria',
    'chocolate_teacher': 'Professor de Chocolate',
    'ice_cream_teacher': 'Professor de Sorvete',
    'bread_teacher': 'Professor de Pão',
    'pizza_teacher': 'Professor de Pizza',
    'sushi_teacher': 'Professor de Sushi',
    'barbecue_teacher': 'Professor de Churrasco',
    'grilling_teacher': 'Professor de Grelhados',
    'smoking_teacher': 'Professor de Defumados',
    'curing_teacher': 'Professor de Cura',
    'fermenting_teacher': 'Professor de Fermentação',
    'brewing_teacher': 'Professor de Cerveja',
    'distilling_teacher': 'Professor de Destilação',
    'aging_teacher': 'Professor de Envelhecimento',
    'blending_teacher': 'Professor de Blend',
    'tasting_teacher': 'Professor de Degustação',
    'pairing_teacher': 'Professor de Harmonização',
    'service_teacher': 'Professor de Atendimento',
    'management_teacher': 'Professor de Gestão',
    'leadership_teacher': 'Professor de Liderança',
    'communication_teacher': 'Professor de Comunicação',
    'presentation_teacher': 'Professor de Apresentação',
    'negotiation_teacher': 'Professor de Negociação',
    'sales_teacher': 'Professor de Vendas',
    'marketing_teacher': 'Professor de Marketing',
    'advertising_teacher': 'Professor de Publicidade',
    'public_relations_teacher': 'Professor de Relações Públicas',
    'branding_teacher': 'Professor de Branding',
    'social_media_teacher': 'Professor de Redes Sociais',
    'content_creation_teacher': 'Professor de Criação de Conteúdo',
    'copywriting_teacher': 'Professor de Copywriting',
    'graphic_design_teacher': 'Professor de Design Gráfico',
    'web_design_teacher': 'Professor de Web Design',
    'ui_design_teacher': 'Professor de Design de Interface',
    'ux_design_teacher': 'Professor de Design de Experiência',
    'product_design_teacher': 'Professor de Design de Produto',
    'industrial_design_teacher': 'Professor de Design Industrial',
    'interior_design_teacher': 'Professor de Design de Interiores',
    'landscape_design_teacher': 'Professor de Paisagismo',
    'fashion_design_teacher': 'Professor de Design de Moda',
    'jewelry_design_teacher': 'Professor de Design de Joias',
    'furniture_design_teacher': 'Professor de Design de Móveis',
    'lighting_design_teacher': 'Professor de Design de Iluminação',
    'sound_design_teacher': 'Professor de Design de Som',
    'video_design_teacher': 'Professor de Design de Vídeo',
    'animation_teacher': 'Professor de Animação',
    'game_design_teacher': 'Professor de Design de Jogos',
    'level_design_teacher': 'Professor de Design de Níveis',
    'character_design_teacher': 'Professor de Design de Personagens',
    'story_teacher': 'Professor de Narrativa',
    'script_teacher': 'Professor de Roteiro',
    'dialogue_teacher': 'Professor de Diálogo',
    'plot_teacher': 'Professor de Enredo',
    'character_development_teacher': 'Professor de Desenvolvimento de Personagens',
    'world_building_teacher': 'Professor de Construção de Mundo',
    'lore_teacher': 'Professor de Lore',
    'mythology_teacher': 'Professor de Mitologia',
    'folklore_teacher': 'Professor de Folclore',
    'legends_teacher': 'Professor de Lendas',
    'fables_teacher': 'Professor de Fábulas',
    'parables_teacher': 'Professor de Parábolas',
    'allegories_teacher': 'Professor de Alegorias',
    'metaphors_teacher': 'Professor de Metáforas',
    'similes_teacher': 'Professor de Símiles',
    'symbolism_teacher': 'Professor de Simbolismo',
    'imagery_teacher': 'Professor de Imagética',
    'tone_teacher': 'Professor de Tom',
    'mood_teacher': 'Professor de Atmosfera',
    'atmosphere_teacher': 'Professor de Atmosfera',
    'ambiance_teacher': 'Professor de Ambiente',
    'vibe_teacher': 'Professor de Vibração',
    'energy_teacher': 'Professor de Energia',
    'spirit_teacher': 'Professor de Espírito',
    'soul_teacher': 'Professor de Alma',
    'heart_teacher': 'Professor de Coração',
    'mind_teacher': 'Professor de Mente',
    'body_teacher': 'Professor de Corpo',
    'spirit_teacher': 'Professor de Espírito',
    'consciousness_teacher': 'Professor de Consciência',
    'awareness_teacher': 'Professor de Consciência',
    'mindfulness_teacher': 'Professor de Atenção Plena',
    'meditation_teacher': 'Professor de Meditação',
    'yoga_teacher': 'Professor de Yoga',
    'pilates_teacher': 'Professor de Pilates',
    'tai_chi_teacher': 'Professor de Tai Chi',
    'qigong_teacher': 'Professor de Qi Gong',
    'martial_arts_teacher': 'Professor de Artes Marciais',
    'karate_teacher': 'Professor de Karatê',
    'judo_teacher': 'Professor de Judô',
    'taekwondo_teacher': 'Professor de Taekwondo',
    'kung_fu_teacher': 'Professor de Kung Fu',
    'boxing_teacher': 'Professor de Boxe',
    'kickboxing_teacher': 'Professor de Kickboxing',
    'muay_thai_teacher': 'Professor de Muay Thai',
    'jiu_jitsu_teacher': 'Professor de Jiu-Jitsu',
    'wrestling_teacher': 'Professor de Luta Livre',
    'fencing_teacher': 'Professor de Esgrima',
    'archery_teacher': 'Professor de Tiro com Arco',
    'shooting_teacher': 'Professor de Tiro',
    'hunting_teacher': 'Professor de Caça',
    'fishing_teacher': 'Professor de Pesca',
    'camping_teacher': 'Professor de Camping',
    'hiking_teacher': 'Professor de Trilha',
    'climbing_teacher': 'Professor de Escalada',
    'mountaineering_teacher': 'Professor de Montanhismo',
    'skiing_teacher': 'Professor de Esqui',
    'snowboarding_teacher': 'Professor de Snowboard',
    'surfing_teacher': 'Professor de Surf',
    'swimming_teacher': 'Professor de Natação',
    'diving_teacher': 'Professor de Mergulho',
    'sailing_teacher': 'Professor de Vela',
    'rowing_teacher': 'Professor de Remo',
    'canoeing_teacher': 'Professor de Canoagem',
    'kayaking_teacher': 'Professor de Caiaque',
    'rafting_teacher': 'Professor de Rafting',
    'tubing_teacher': 'Professor de Tubing',
    'waterskiing_teacher': 'Professor de Esqui Aquático',
    'wakeboarding_teacher': 'Professor de Wakeboard',
    'kitesurfing_teacher': 'Professor de Kitesurf',
    'windsurfing_teacher': 'Professor de Windsurf',
    'paddleboarding_teacher': 'Professor de Stand Up Paddle',
    'bodyboarding_teacher': 'Professor de Bodyboard',
    'bodysurfing_teacher': 'Professor de Bodysurf',
    'snorkeling_teacher': 'Professor de Snorkel',
    'freediving_teacher': 'Professor de Apneia',
    'scuba_diving_teacher': 'Professor de Mergulho Autônomo',
    'technical_diving_teacher': 'Professor de Mergulho Técnico',
    'cave_diving_teacher': 'Professor de Mergulho em Caverna',
    'wreck_diving_teacher': 'Professor de Mergulho em Naufrágio',
    'night_diving_teacher': 'Professor de Mergulho Noturno',
    'deep_diving_teacher': 'Professor de Mergulho Profundo',
    'altitude_diving_teacher': 'Professor de Mergulho em Altitude',
    'ice_diving_teacher': 'Professor de Mergulho no Gelo',
    'dry_suit_diving_teacher': 'Professor de Mergulho com Roupa Seca',
    'rebreather_diving_teacher': 'Professor de Mergulho com Rebreather',
    'mixed_gas_diving_teacher': 'Professor de Mergulho com Mistura de Gases',
    'nitrox_diving_teacher': 'Professor de Mergulho com Nitrox',
    'trimix_diving_teacher': 'Professor de Mergulho com Trimix',
    'heliox_diving_teacher': 'Professor de Mergulho com Heliox',
    'argon_diving_teacher': 'Professor de Mergulho com Argônio',
    'neon_diving_teacher': 'Professor de Mergulho com Neônio',
    'xenon_diving_teacher': 'Professor de Mergulho com Xenônio',
    'krypton_diving_teacher': 'Professor de Mergulho com Criptônio',
    'radon_diving_teacher': 'Professor de Mergulho com Radônio',
    'hydrogen_diving_teacher': 'Professor de Mergulho com Hidrogênio',
    'helium_diving_teacher': 'Professor de Mergulho com Hélio',
    'lithium_diving_teacher': 'Professor de Mergulho com Lítio',
    'sodium_diving_teacher': 'Professor de Mergulho com Sódio',
    'potassium_diving_teacher': 'Professor de Mergulho com Potássio',
    'rubidium_diving_teacher': 'Professor de Mergulho com Rubídio',
    'cesium_diving_teacher': 'Professor de Mergulho com Césio',
    'francium_diving_teacher': 'Professor de Mergulho com Frâncio',
    'beryllium_diving_teacher': 'Professor de Mergulho com Berílio',
    'magnesium_diving_teacher': 'Professor de Mergulho com Magnésio',
    'calcium_diving_teacher': 'Professor de Mergulho com Cálcio',
    'strontium_diving_teacher': 'Professor de Mergulho com Estrôncio',
    'barium_diving_teacher': 'Professor de Mergulho com Bário',
    'radium_diving_teacher': 'Professor de Mergulho com Rádio',
    'scandium_diving_teacher': 'Professor de Mergulho com Escândio',
    'yttrium_diving_teacher': 'Professor de Mergulho com Ítrio',
    'lanthanum_diving_teacher': 'Professor de Mergulho com Lantânio',
    'actinium_diving_teacher': 'Professor de Mergulho com Actínio',
    'titanium_diving_teacher': 'Professor de Mergulho com Titânio',
    'zirconium_diving_teacher': 'Professor de Mergulho com Zircônio',
    'hafnium_diving_teacher': 'Professor de Mergulho com Háfnio',
    'rutherfordium_diving_teacher': 'Professor de Mergulho com Rutherfórdio',
    'vanadium_diving_teacher': 'Professor de Mergulho com Vanádio',
    'niobium_diving_teacher': 'Professor de Mergulho com Nióbio',
    'tantalum_diving_teacher': 'Professor de Mergulho com Tântalo',
    'dubnium_diving_teacher': 'Professor de Mergulho com Dúbnio',
    'chromium_diving_teacher': 'Professor de Mergulho com Cromo',
    'molybdenum_diving_teacher': 'Professor de Mergulho com Molibdênio',
    'tungsten_diving_teacher': 'Professor de Mergulho com Tungstênio',
    'seaborgium_diving_teacher': 'Professor de Mergulho com Seabórgio',
    'manganese_diving_teacher': 'Professor de Mergulho com Manganês',
    'technetium_diving_teacher': 'Professor de Mergulho com Tecnécio',
    'rhenium_diving_teacher': 'Professor de Mergulho com Rênio',
    'bohrium_diving_teacher': 'Professor de Mergulho com Bóhrio',
    'iron_diving_teacher': 'Professor de Mergulho com Ferro',
    'ruthenium_diving_teacher': 'Professor de Mergulho com Rutênio',
    'osmium_diving_teacher': 'Professor de Mergulho com Ósmio',
    'hassium_diving_teacher': 'Professor de Mergulho com Hássio',
    'cobalt_diving_teacher': 'Professor de Mergulho com Cobalto',
    'rhodium_diving_teacher': 'Professor de Mergulho com Ródio',
    'iridium_diving_teacher': 'Professor de Mergulho com Irídio',
    'meitnerium_diving_teacher': 'Professor de Mergulho com Meitnério',
    'nickel_diving_teacher': 'Professor de Mergulho com Níquel',
    'palladium_diving_teacher': 'Professor de Mergulho com Paládio',
    'platinum_diving_teacher': 'Professor de Mergulho com Platina',
    'darmstadtium_diving_teacher': 'Professor de Mergulho com Darmstádtio',
    'copper_diving_teacher': 'Professor de Mergulho com Cobre',
    'silver_diving_teacher': 'Professor de Mergulho com Prata',
    'gold_diving_teacher': 'Professor de Mergulho com Ouro',
    'roentgenium_diving_teacher': 'Professor de Mergulho com Roentgênio',
    'zinc_diving_teacher': 'Professor de Mergulho com Zinco',
    'cadmium_diving_teacher': 'Professor de Mergulho com Cádmio',
    'mercury_diving_teacher': 'Professor de Mergulho com Mercúrio',
    'copernicium_diving_teacher': 'Professor de Mergulho com Copernício',
    'aluminum_diving_teacher': 'Professor de Mergulho com Alumínio',
    'gallium_diving_teacher': 'Professor de Mergulho com Gálio',
    'indium_diving_teacher': 'Professor de Mergulho com Índio',
    'tin_diving_teacher': 'Professor de Mergulho com Estanho',
    'thallium_diving_teacher': 'Professor de Mergulho com Tálio',
    'lead_diving_teacher': 'Professor de Mergulho com Chumbo',
    'bismuth_diving_teacher': 'Professor de Mergulho com Bismuto',
    'polonium_diving_teacher': 'Professor de Mergulho com Polônio',
    'astatine_diving_teacher': 'Professor de Mergulho com Astato',
    'radon_diving_teacher': 'Professor de Mergulho com Radônio',
    'francium_diving_teacher': 'Professor de Mergulho com Frâncio',
    'radium_diving_teacher': 'Professor de Mergulho com Rádio',
    'actinium_diving_teacher': 'Professor de Mergulho com Actínio',
    'thorium_diving_teacher': 'Professor de Mergulho com Tório',
    'protactinium_diving_teacher': 'Professor de Mergulho com Protactínio',
    'uranium_diving_teacher': 'Professor de Mergulho com Urânio',
    'neptunium_diving_teacher': 'Professor de Mergulho com Neptúnio',
    'plutonium_diving_teacher': 'Professor de Mergulho com Plutônio',
    'americium_diving_teacher': 'Professor de Mergulho com Amerício',
    'curium_diving_teacher': 'Professor de Mergulho com Cúrio',
    'berkelium_diving_teacher': 'Professor de Mergulho com Berquélio',
    'californium_diving_teacher': 'Professor de Mergulho com Califórnio',
    'einsteinium_diving_teacher': 'Professor de Mergulho com Einstênio',
    'fermium_diving_teacher': 'Professor de Mergulho com Férmio',
    'mendelevium_diving_teacher': 'Professor de Mergulho com Mendelévio',
    'nobelium_diving_teacher': 'Professor de Mergulho com Nobélio',
    'lawrencium_diving_teacher': 'Professor de Mergulho com Laurêncio',
    'rutherfordium_diving_teacher': 'Professor de Mergulho com Rutherfórdio',
    'dubnium_diving_teacher': 'Professor de Mergulho com Dúbnio',
    'seaborgium_diving_teacher': 'Professor de Mergulho com Seabórgio',
    'bohrium_diving_teacher': 'Professor de Mergulho com Bóhrio',
    'hassium_diving_teacher': 'Professor de Mergulho com Hássio',
    'meitnerium_diving_teacher': 'Professor de Mergulho com Meitnério',
    'darmstadtium_diving_teacher': 'Professor de Mergulho com Darmstádtio',
    'roentgenium_diving_teacher': 'Professor de Mergulho com Roentgênio',
    'copernicium_diving_teacher': 'Professor de Mergulho com Copernício',
    'nihonium_diving_teacher': 'Professor de Mergulho com Nihônio',
    'flerovium_diving_teacher': 'Professor de Mergulho com Fleróvio',
    'moscovium_diving_teacher': 'Professor de Mergulho com Moscóvio',
    'livermorium_diving_teacher': 'Professor de Mergulho com Livermório',
    'tennessine_diving_teacher': 'Professor de Mergulho com Tenesso',
    'oganesson_diving_teacher': 'Professor de Mergulho com Oganésson'
}

def get_config() -> Dict[str, Any]:
    """Retorna todas as configurações"""
    return {
        'api': API_CONFIG,
        'search': SEARCH_CONFIG,
        'export': EXPORT_CONFIG,
        'logging': LOGGING_CONFIG,
        'fields': DEFAULT_FIELDS,
        'business_types': BUSINESS_TYPE_MAPPING
    }

def get_api_key() -> str:
    """Retorna a chave da API das variáveis de ambiente"""
    return os.getenv('GOOGLE_PLACES_API_KEY', '')

def is_configured() -> bool:
    """Verifica se a aplicação está configurada"""
    return bool(get_api_key())

def get_business_type_translation(english_type: str) -> str:
    """Traduz tipo de negócio do inglês para português"""
    return BUSINESS_TYPE_MAPPING.get(english_type, english_type)
